apiVersion: apps/v1
kind: Deployment
metadata: { name: {{ .Release.Name }}-backend, labels: { app: {{ .Release.Name }}-backend } }
spec:
  replicas: {{ .Values.backend.replicas }}
  selector: { matchLabels: { app: {{ .Release.Name }}-backend } }
  template:
    metadata: { labels: { app: {{ .Release.Name }}-backend } }
    spec:
      serviceAccountName: {{ include "pulsesg-ai-task-manager.serviceAccountName" . }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports: [{ name: http, containerPort: 8080 }]
          envFrom: [{ secretRef: { name: {{ .Values.backend.secret.existingSecret }} } }, { configMapRef: { name: {{ include "pulsesg-ai-task-manager.fullname" . }}-config } }]
          resources: {{- toYaml .Values.backend.resources | nindent 12 }}
          readinessProbe: { httpGet: { path: /support/actuator/health, port: http }, initialDelaySeconds: 20, periodSeconds: 10 }
          livenessProbe: { httpGet: { path: /support/actuator/health, port: http }, initialDelaySeconds: 30, periodSeconds: 20 }
