{{- if .Values.ingress.enabled }}apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pulsesg-ai-task-manager.fullname" . }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service: { name: {{ include "pulsesg-ai-task-manager.fullname" $ }}, port: { name: {{ .portName }} } }
        {{- end }}
{{- end }}
