{{- if .Values.backend.secret.create }}
apiVersion: v1
kind: Secret
metadata: { name: {{ .Values.backend.secret.existingSecret }} }
type: Opaque
stringData:
  DB_URL: {{ .Values.backend.secret.dbUrl | quote }}
  DB_USERNAME: {{ .Values.backend.secret.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.backend.secret.dbPassword | quote }}
  JWT_SECRET: {{ .Values.backend.secret.jwtSecret | quote }}
{{- end }}
