nameOverride: pulsesg-ai-task-manager
namespace: pulsesg-dev
replicaCount: 1
frontend:
  image: { repository: 385168913795.dkr.ecr.ap-south-1.amazonaws.com/pulsesg-ai-task-manager-frontend, tag: v1.0.0, pullPolicy: IfNotPresent }
  apiBaseUrl: /support/api
  basePath: /support/
  containerPort: 80
  service: { port: 80 }
  resources: { requests: { cpu: 50m, memory: 64Mi }, limits: { cpu: 250m, memory: 256Mi } }
backend:
  image: { repository: 385168913795.dkr.ecr.ap-south-1.amazonaws.com/pulsesg-ai-task-manager-backend, tag: v1.0.0, pullPolicy: IfNotPresent }
  containerPort: 8080
  service: { port: 8080 }
  resources: { requests: { cpu: 100m, memory: 256Mi }, limits: { cpu: 500m, memory: 512Mi } }
  env: { corsOrigins: https://lokeshwaffle.in, contextPath: /support }
  secret: { existingSecret: pulsesg-ai-task-manager-db, create: false, dbUrl: "", dbUsername: "", dbPassword: "", jwtSecret: "" }
imagePullSecrets: []
serviceAccount: { create: true, name: "" }
ingress:
  enabled: true
  className: alb
  host: lokeshwaffle.in
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /support/actuator/health
    alb.ingress.kubernetes.io/group.name: pulsesg-dev
    alb.ingress.kubernetes.io/group.order: "10"
  paths:
    - path: /support/api
      pathType: Prefix
      portName: http-backend
    - path: /support
      pathType: Prefix
      portName: http-frontend
